import React from "react";
import Header from "../Header";
import { MuiDivider, MuiMainBox } from "../../styles/StyledComponents";
import Head from "next/head";

const todo = ({ children, heading }) => {
  return (
    <>
      <Head>
        <title>JASONPlaceholder - 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiMainBox>
        <Header heading={heading} />
        <MuiDivider />
        {children}
      </MuiMainBox>
    </>
  );
};

export default todo;
